# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  steps:
    - step: &test
        name: Test
        image: kazssym/xllmnrd-builder:gcc
        script:
          - autoreconf --install
          - ./configure --prefix=/opt/xllmnrd
          - make check
pipelines:
  branches:
    master:
      - step: *test
  pull-requests:
    "**":
      - step: *test
