# Docker compose file to build XLLMNRD in a container
# Copyright (C) 2017-2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "2.1"
services:
  build:
    build: etc/gcc
    image: kazssym/xllmnrd-builder:gcc
    network_mode: host
    volumes:
      - .:/usr/src/xllmnrd
    working_dir: /usr/src/xllmnrd/build
    command: make check
      CFLAGS="-g -O2 -Wpedantic -Wall"
      CXXFLAGS="-g -O2 -Wpedantic -Wall"
