# docker-compose.yml
# Copyright (C) 2017-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "2.4"
services:
  builder:
    build:
      context: docker/gcc
    image: kazssym/xllmnrd-builder:gcc
    network_mode: host
    volumes:
      - .:/usr/src/xllmnrd
    working_dir: /usr/src/xllmnrd
    command: make
