# Docker compose file to build XLLMNRD 
# Copyright (C) 2017 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
---
version: "3"
services:
  builder:
    build: etc/builder
    image: kazssym/xllmnrd-builder:latest
    network_mode: host
    volumes:
      - .:/usr/src/xllmnrd
    working_dir: /usr/src/xllmnrd
    command: make
